# Managed by Hydra

hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  - data: base
  - model: base

experiment_name: run_1
output_folder: output
exp_output_root_path: ${output_folder}/${data.dataset}/${experiment_name}

global_train_seed: 12345
global_test_seed: 32102